#!/bin/bash

cd $(dirname `readlink -f $0`)

cat js/jquery.min.js js/jquery.jplayer.min.js js/add-on/jplayer.playlist.min.js \
        js/bootstrap.min.js js/app.js > js/squashed.js

cat css/bootstrap.min.css css/bootstrap-theme.min.css css/screen.css > css/squashed.css
