// Code generated by counterfeiter. DO NOT EDIT.
package assertfakes

import (
	"sync"

	"github.com/ironsmile/euterpe/src/assert"
)

type FakeTestingErrf struct {
	ErrorfStub        func(string, ...any)
	errorfMutex       sync.RWMutex
	errorfArgsForCall []struct {
		arg1 string
		arg2 []any
	}
	HelperStub        func()
	helperMutex       sync.RWMutex
	helperArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTestingErrf) Errorf(arg1 string, arg2 ...any) {
	fake.errorfMutex.Lock()
	fake.errorfArgsForCall = append(fake.errorfArgsForCall, struct {
		arg1 string
		arg2 []any
	}{arg1, arg2})
	stub := fake.ErrorfStub
	fake.recordInvocation("Errorf", []interface{}{arg1, arg2})
	fake.errorfMutex.Unlock()
	if stub != nil {
		fake.ErrorfStub(arg1, arg2...)
	}
}

func (fake *FakeTestingErrf) ErrorfCallCount() int {
	fake.errorfMutex.RLock()
	defer fake.errorfMutex.RUnlock()
	return len(fake.errorfArgsForCall)
}

func (fake *FakeTestingErrf) ErrorfCalls(stub func(string, ...any)) {
	fake.errorfMutex.Lock()
	defer fake.errorfMutex.Unlock()
	fake.ErrorfStub = stub
}

func (fake *FakeTestingErrf) ErrorfArgsForCall(i int) (string, []any) {
	fake.errorfMutex.RLock()
	defer fake.errorfMutex.RUnlock()
	argsForCall := fake.errorfArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTestingErrf) Helper() {
	fake.helperMutex.Lock()
	fake.helperArgsForCall = append(fake.helperArgsForCall, struct {
	}{})
	stub := fake.HelperStub
	fake.recordInvocation("Helper", []interface{}{})
	fake.helperMutex.Unlock()
	if stub != nil {
		fake.HelperStub()
	}
}

func (fake *FakeTestingErrf) HelperCallCount() int {
	fake.helperMutex.RLock()
	defer fake.helperMutex.RUnlock()
	return len(fake.helperArgsForCall)
}

func (fake *FakeTestingErrf) HelperCalls(stub func()) {
	fake.helperMutex.Lock()
	defer fake.helperMutex.Unlock()
	fake.HelperStub = stub
}

func (fake *FakeTestingErrf) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.errorfMutex.RLock()
	defer fake.errorfMutex.RUnlock()
	fake.helperMutex.RLock()
	defer fake.helperMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTestingErrf) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ assert.TestingErrf = new(FakeTestingErrf)
