// Code generated by counterfeiter. DO NOT EDIT.
package assertfakes

import (
	"sync"

	"github.com/ironsmile/euterpe/src/assert"
)

type FakeTestingFatalf struct {
	FatalfStub        func(string, ...any)
	fatalfMutex       sync.RWMutex
	fatalfArgsForCall []struct {
		arg1 string
		arg2 []any
	}
	HelperStub        func()
	helperMutex       sync.RWMutex
	helperArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTestingFatalf) Fatalf(arg1 string, arg2 ...any) {
	fake.fatalfMutex.Lock()
	fake.fatalfArgsForCall = append(fake.fatalfArgsForCall, struct {
		arg1 string
		arg2 []any
	}{arg1, arg2})
	stub := fake.FatalfStub
	fake.recordInvocation("Fatalf", []interface{}{arg1, arg2})
	fake.fatalfMutex.Unlock()
	if stub != nil {
		fake.FatalfStub(arg1, arg2...)
	}
}

func (fake *FakeTestingFatalf) FatalfCallCount() int {
	fake.fatalfMutex.RLock()
	defer fake.fatalfMutex.RUnlock()
	return len(fake.fatalfArgsForCall)
}

func (fake *FakeTestingFatalf) FatalfCalls(stub func(string, ...any)) {
	fake.fatalfMutex.Lock()
	defer fake.fatalfMutex.Unlock()
	fake.FatalfStub = stub
}

func (fake *FakeTestingFatalf) FatalfArgsForCall(i int) (string, []any) {
	fake.fatalfMutex.RLock()
	defer fake.fatalfMutex.RUnlock()
	argsForCall := fake.fatalfArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeTestingFatalf) Helper() {
	fake.helperMutex.Lock()
	fake.helperArgsForCall = append(fake.helperArgsForCall, struct {
	}{})
	stub := fake.HelperStub
	fake.recordInvocation("Helper", []interface{}{})
	fake.helperMutex.Unlock()
	if stub != nil {
		fake.HelperStub()
	}
}

func (fake *FakeTestingFatalf) HelperCallCount() int {
	fake.helperMutex.RLock()
	defer fake.helperMutex.RUnlock()
	return len(fake.helperArgsForCall)
}

func (fake *FakeTestingFatalf) HelperCalls(stub func()) {
	fake.helperMutex.Lock()
	defer fake.helperMutex.Unlock()
	fake.HelperStub = stub
}

func (fake *FakeTestingFatalf) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.fatalfMutex.RLock()
	defer fake.fatalfMutex.RUnlock()
	fake.helperMutex.RLock()
	defer fake.helperMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTestingFatalf) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ assert.TestingFatalf = new(FakeTestingFatalf)
