#!/bin/bash
set -e

cd $(dirname `readlink -f $0`)
cd ..

os='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   os='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   os='freebsd'
elif [[ "$unamestr" == 'Darwin' ]]; then
    os='darwin'
fi

arch="amd64"
version=`git describe --tags --always`

if [[ $# -gt 0 ]]; then
    export GOOS="$1"
    os="$GOOS"
fi

if [ -d dist/httpms ]
then
    echo "Removing old dist/httpms directory..."
    rm -rf dist/httpms
fi

echo "Making dist directory..."
mkdir -p dist/httpms

echo "Building binaries..."
make release
mv httpms dist/httpms/httpms

for file in README.md
do
    echo "Copying $file..."
    cp "$file" dist/httpms
done

echo "Copying install/uninstall scripts..."
cp tools/install dist/httpms
cp tools/uninstall dist/httpms

archive="httpms_${version}_${os}_${arch}.tar.gz"

echo "Creating archive..."
cd dist
tar cfzv "$archive" httpms

echo "dist/$archive created"

echo "Cleaning up..."
cd -
rm -rf dist/httpms || exit

echo "Done"
