#!/bin/bash
INSTALL_DIR=$(dirname `readlink -f $0`)
cd "$INSTALL_DIR"
cd ..

if [ -d /etc/euterpe ]; then
    echo "Euterpe is already installed. Aborting."
    exit 0
fi

for binary in euterpe
do
    if [ -f "/usr/bin/${binary}" ]; then
        echo "Euterpe is already installed. Aborting."
        exit 0
    fi
done

echo "Installing euterpe dir to /etc/..."
cp -a "$INSTALL_DIR" /etc/euterpe || exit 1

echo "Setting directory permissions..."
find /etc/euterpe -type d -exec chmod 755 "{}" \; || exit 1

echo "Moving binaries to /usr/bin/..."
mv /etc/euterpe/euterpe /usr/bin/euterpe || exit 1

echo "Done"
