name: Continuous Integration
on: [push, pull_request]
jobs:

  build:
    name: Build, test and lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
      id: go

    - name: Install OS dependencies
      run: sudo apt-get install libtagc0-dev upx-ucl

    - name: Build
      run: |
        make release

    - name: Unit Tests
      run: |
        go test ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.64.8

    - name: Build Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: false

  cover:
    name: Code Test Coverage
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Install OS dependencies
      run: sudo apt-get install libtagc0-dev upx-ucl

    - name: Generate cover profile
      run: |
        go test -race -covermode atomic -coverprofile=covprofile.tmp ./...
        grep -v 'fakes/' covprofile.tmp > covprofile

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: covprofile
