name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
      id: go

    - name: Install OS dependencies
      run: sudo apt-get install libtagc0-dev upx-ucl

    - name: Build Release Bundle
      id: linux_bundle
      run: |
        ./tools/build

    - name: Upload Linux (amd64) Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-amd64
        path: dist/euterpe_*.tar.gz

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
      id: go

    - name: Install OS dependencies
      run: |
        brew update
        brew install libtag upx

    - name: Build Release Bundle
      id: macos_bundle
      run: |
        ./tools/build

    - name: Upload macOS (amd64) Artifact
      uses: actions/upload-artifact@v3
      with:
        name: macos-amd64
        path: dist/euterpe_*.tar.gz

  # # https://github.com/taglib/taglib/blob/master/INSTALL.md
  # build-windows:
  #   name: Build Windows
  #   runs-on: windows-latest
  #   steps:

  #     - name: Install Dev Tools
  #     - run: |
  #       choco install golang
  #       choco install cmake
  #       choco install make
  #       choco install mingw
  #       choco install gzip
  #       choco install tartool
  #       choco install upx

  #     - name: Install Taglib
  #     - run: |
  #       cd ~\Downloads
  #       curl -o taglib.tar.gz https://taglib.org/releases/taglib-1.12.tar.gz
  #       tar xf taglib.tar.gz
  #       cd taglib-1.12
  #       cmake -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\g++.exe -DCMAKE_C_COMPILER=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\gcc.exe -DCMAKE_MAKE_PROGRAM=make.exe  -DCMAKE_INSTALL_PREFIX=C:\Libraries\taglib .

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-macos, build-linux]
    steps:
      # Use download-artifact: https://github.com/actions/download-artifact

      - name: Download Linux (amd64) Build
        uses: actions/download-artifact@v2
        with:
          name: linux-amd64

      - name: Download macOS (amd64) Build
        uses: actions/download-artifact@v2
        with:
          name: macos-amd64

      - name: Set Outputs For Uploads
        id: files_to_upload
        run: |
          ls -R
          linux_file_amd64=$(ls euterpe_*linux*.tar.gz)
          macos_file_amd64=$(ls euterpe_*darwin*.tar.gz)
          echo ::set-output "name=version::${GITHUB_REF#refs/*/}"
          echo ::set-output "name=linux_file_amd64::${linux_file_amd64}"
          echo ::set-output "name=macos_file_amd64::${macos_file_amd64}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.files_to_upload.outputs.version }}
          body: |
            ## Changes in this release

            - TODO: add changes

            ## Installation

            Download the archive for your OS below, extract it and
            follow the instructions in the README.
          draft: true
          prerelease: false

      - name: Upload Linux (amd64)
        id: upload-linux-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's
          # ID to get its outputs object, which include a `upload_url`.
          # See this blog post for more info:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.files_to_upload.outputs.linux_file_amd64 }}
          asset_name: ${{ steps.files_to_upload.outputs.linux_file_amd64 }}
          asset_content_type: application/x-compressed-tar

      - name: Upload macOS (amd64)
        id: upload-macos-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.files_to_upload.outputs.macos_file_amd64 }}
          asset_name: ${{ steps.files_to_upload.outputs.macos_file_amd64 }}
          asset_content_type: application/x-compressed-tar
